services:
  - type: web
    name: smart-home-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "5000"
    plan: starter
    ports:
      - port: 5000
        protocol: http
      - port: 8501
        protocol: http
